name: Olá Mundo

on: [push, workflow_dispatch]

jobs:
  ola_mundo:
    runs-on: ubuntu-latest

    steps:
      - name: Diga Olá
        run: echo "Olá, Mundo!, a variável nome do projeto é ${{ vars.nome_projeto }}"
