name: Olá Mundo

run-name: Olá Mundo separando desenvolvimento e produção

on: [push, workflow_dispatch]

jobs:
  ola_mundo_devl:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    environment:
      name: devl

    steps:
      - name: Diga Olá
        run: echo "Estamos dando olá ao ambiente de desenvolvimento" >> $GITHUB_STEP_SUMMARY

  ola_mundo_prod:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment:
      name: prod

    steps:
      - name: Diga Olá
        run: echo "Estamos dando olá ao ambiente de produção" >> $GITHUB_STEP_SUMMARY
