name: Olá Mundo

run-name: Olá Mundo desenvolvimento e produção

on: [push, workflow_dispatch]

jobs:
  ola_mundo_devl:
    runs-on: ubuntu-latest
    environment:
      name: devl

    steps:
      - name: Diga Olá
        run: echo "Estamos dando olá ao ambiente de desenvolvimento" >> $GITHUB_STEP_SUMMARY

  ola_mundo_prod:
    runs-on: ubuntu-latest
    environment:
      name: prod

    steps:
      - name: Diga Olá
        run: echo "Estamos dando olá ao ambiente de produção" >> $GITHUB_STEP_SUMMARY
